from .agnostic_explainer import AgnosticExplainer
import numpy as np
import numpy.typing as npt
from matplotlib.axes import Axes
import matplotlib.pyplot as plt
from ...utils.validate_input import validate_input_2d

class PDPExplainer(AgnosticExplainer):
    def __init__(self, input_model):
        super().__init__(input_model)
        
    def explain(
        self,
        X: npt.NDArray,
        feature_idx: int = None,
        n_grid: int = 50
    ) -> npt.NDArray:
        """Computes the PDP results for the data.

        Parameters
        ----------
        data : npt.NDArray
            Samples form the data generating distribution, (n_samples, n_features).
        feature_idx : int, optional
            Column index of the feature to explain, by default None
        n_grid : int, optional
            Number of data points generated by the PDP explanation, by default 50

        Returns
        -------
        npt.NDArray
            The marginalised effect of the given feature, (n_grid, n_features) or (n_grid).
            
        Raises
        ------
        TypeError
            If data is not a numpy array.
        ValueError
            If data is not two-dimensional.
        """
        
        X = validate_input_2d(X)
                
        if feature_idx is not None:
            return self._compute_pdp(X, feature_idx, n_grid)
        else:
            pdp_results = []
            for feature_idx in range(X.shape[-1]):
                result = self._compute_pdp(X, feature_idx, n_grid)
                pdp_results.append(result)
            
            return np.array(pdp_results)
        
    def plot(
        self, 
        X: npt.NDArray,
        feature_idx: int, 
        output_idx: int = 0, 
        n_grid: int = 50,
        ax: Axes = None,
        feature_name: str = None,
    ) -> Axes:
        """Produce visual PDP plots for a given feature and output index

        Parameters
        ----------
        data : npt.NDArray
            All data points to explain, (n_samples, n_features).
        feature_idx : int
            Column index of the feature to explain.
        output_idx : int
            Since model may have multiple outputs (e.g. multi-class), an index of the output to explain can be specified.
        n_grid : int, optional
            Number of data points generated for the PDP explanation, by default 50.
        ax : Axes, optional
            Axes on which to draw the plot. If None, a new figure and axes are created., by default None
        feature_name : str, optional
            Name of the feature, used for labelling the x-axis, by default None

        Returns
        -------
        Axes
            The axes containing the PDP plot.

        Raises
        ------
        TypeError
            If data is not a numpy array.
        ValueError
            If data is not two-dimensional.
        """
        
        X = validate_input_2d(X)
        
        X_pdp = self.explain(X, feature_idx, n_grid)
        X_pdp = X_pdp[:, output_idx] if X_pdp.ndim > 1 else X_pdp
        
        xj = X[:, feature_idx]
        min_xj, max_xj = xj.min(), xj.max()
        
        grid = np.linspace(min_xj, max_xj, n_grid, dtype=X.dtype)
        
        if ax is None:
            _, ax = plt.subplots()
        
        ax.plot(grid, X_pdp)
        ax.grid()
        ax.set_xlabel(feature_name)
        ax.set_ylabel("Prediction")
        ax.set_title("PDP Plot")
        
        return ax
        
    
    def _compute_pdp(self, data, feature_idx, n_grid):
        """Used for computing all model predictions for one varying feature for all data points"""
        xj = data[:, feature_idx]
        min_xj, max_xj = xj.min(), xj.max()
        
        grid = np.linspace(min_xj, max_xj, n_grid, dtype=data.dtype)
        
        n_samples = data.shape[0]
        X_pdp = np.repeat(data, n_grid, axis=0)
        X_pdp[:, feature_idx] = np.tile(grid, n_samples)
        
        pred = self.model(X_pdp)
        
        if pred.ndim == 1:
            pred = pred.reshape(n_samples, n_grid)
        else:
            pred = pred.reshape(n_samples, n_grid, -1)
            
        return pred.mean(axis=0)